prettier formatted yaml

diff --git a/_YAML/CiscoAnyConnect/CiscoAnyConnect.pkg.recipe.yaml b/_YAML/CiscoAnyConnect/CiscoAnyConnect.pkg.recipe.yaml
--- a/_YAML/CiscoAnyConnect/CiscoAnyConnect.pkg.recipe.yaml
+++ b/_YAML/CiscoAnyConnect/CiscoAnyConnect.pkg.recipe.yaml
@@ -56,7 +56,20 @@ Process:
 
 - Processor: FileCreator
   Arguments:
-    file_content: "#!/bin/bash\n## script to install and activate Cisco AnyConnect\n\nDIR=$(dirname \"$0\")\n\n/usr/sbin/installer -applyChoiceChangesXML \"$DIR/choices.xml\" -pkg \"$DIR/AnyConnect.pkg\" -target /\n\nif (test $? = 0) then\n    echo \"Cisco AnyConnect installed.\"\nelse\n    echo \"ERROR: Cisco AnyConnect installation failed.\"\n    exit 1\nfi\n"
+    file_content: |
+      #!/bin/bash
+      ## script to install and activate Cisco AnyConnect
+      
+      DIR=$(dirname "$0")
+      
+      /usr/sbin/installer -applyChoiceChangesXML "$DIR/choices.xml" -pkg "$DIR/AnyConnect.pkg" -target /
+      
+      if (test $? = 0) then
+          echo "Cisco AnyConnect installed."
+      else
+          echo "ERROR: Cisco AnyConnect installation failed."
+          exit 1
+      fi
     file_mode: '0755'
     file_path: '%RECIPE_CACHE_DIR%/Scripts/postinstall'
 
diff --git a/_YAML/JMP/JMP.pkg.recipe.yaml b/_YAML/JMP/JMP.pkg.recipe.yaml
--- a/_YAML/JMP/JMP.pkg.recipe.yaml
+++ b/_YAML/JMP/JMP.pkg.recipe.yaml
@@ -1,4 +1,6 @@
-Description: "Creates a package from a pre-downloaded JMP installer which has already been installed on a client, and the SIP file converted to a JMP.per file as per the instructions in the JMP Deployment Guide.\nYou need to manually supply the JMP version, since attempts to extract this from the installer have so far failed.\n"
+Description: |
+  Creates a package from a pre-downloaded JMP installer which has already been installed on a client, and the SIP file converted to a JMP.per file as per the instructions in the JMP Deployment Guide.
+  You need to manually supply the JMP version, since attempts to extract this from the installer have so far failed.
 Identifier: com.github.grahampugh.recipes.pkg.JMP
 MinimumVersion: 1.0.0
 
@@ -25,7 +27,51 @@ Process:
 
 - Processor: FileCreator
   Arguments:
-    file_content: "#!/bin/bash\nDIR=$(dirname \"$0\")\nMAJOR=$(echo \"%JMP_VERSION%\" | cut -d\".\" -f1)\nMINOR=$(echo \"%JMP_VERSION%\" | cut -d\".\" -f2)\n\n# attach main image\necho \"Mounting JMP image\"\nhdiutil attach ${DIR}/JMP_${MAJOR}.dmg -nobrowse\n\n# attach installer image, located inside main image\necho \"Mounting JMP installer image\"\nhdiutil attach /Volumes/JMP_${MAJOR}_${MINOR}/JMP/JMP/${MAJOR}_${MINOR}/Macintosh/JMP-Install.dmg -nobrowse\n\n# install JMP with Company License\ninstaller -target / -pkg \"/Volumes/JMP-${MAJOR}-Installer/JMP ${MAJOR}.pkg\"\n\n# eject mounted JMP volumes\nfor path in /Volumes/JMP*; do\n    [ -d \"${path}\" ] || continue # if not a directory, skip\n    dirname=\"$(basename \"${path}\")\"\n    hdiutil eject ${path}\ndone\n\n# relocate license\nif [[ -f \"$HOME/Library/Application Support/JMP/${MAJOR}/JMP.per\" ]]; then\n    /bin/mv \"$HOME/Library/Application Support/JMP/${MAJOR}/JMP.per\" \\\n    \"/Library/Application Support/JMP/${MAJOR}/JMP.per\"\nelif [[ -f \"/var/root/Library/Application Support/JMP/${MAJOR}/JMP.per\" ]]; then\n    /bin/mkdir -p \"/Library/Application Support/JMP/${MAJOR}\"\n    /bin/mv \"/var/root/Library/Application Support/JMP/${MAJOR}/JMP.per\" \\\n    \"/Library/Application Support/JMP/${MAJOR}/JMP.per\"\n    # change permissions\n    /bin/chmod 644 \"/Library/Application Support/JMP/${MAJOR}/JMP.per\"\nelse\n    echo \"ERROR: JMP.per not found\"\n    exit 1\nfi\nif [[ -f \"/Library/Application Support/JMP/${MAJOR}/JMP.per\" ]]; then\n    # define license location\n    /usr/bin/defaults write \"/Library/Preferences/com.sas.jmp.plist\" Setinit_${MAJOR}_Path \"/Library/Application Support/JMP/${MAJOR}/JMP.per\"\nelse\n    echo \"ERROR: JMP.per not found in Library folder\"\n    exit 1\nfi\n"
+    file_content: |
+      #!/bin/bash
+      DIR=$(dirname "$0")
+      MAJOR=$(echo "%JMP_VERSION%" | cut -d"." -f1)
+      MINOR=$(echo "%JMP_VERSION%" | cut -d"." -f2)
+      
+      # attach main image
+      echo "Mounting JMP image"
+      hdiutil attach ${DIR}/JMP_${MAJOR}.dmg -nobrowse
+      
+      # attach installer image, located inside main image
+      echo "Mounting JMP installer image"
+      hdiutil attach /Volumes/JMP_${MAJOR}_${MINOR}/JMP/JMP/${MAJOR}_${MINOR}/Macintosh/JMP-Install.dmg -nobrowse
+      
+      # install JMP with Company License
+      installer -target / -pkg "/Volumes/JMP-${MAJOR}-Installer/JMP ${MAJOR}.pkg"
+      
+      # eject mounted JMP volumes
+      for path in /Volumes/JMP*; do
+          [ -d "${path}" ] || continue # if not a directory, skip
+          dirname="$(basename "${path}")"
+          hdiutil eject ${path}
+      done
+      
+      # relocate license
+      if [[ -f "$HOME/Library/Application Support/JMP/${MAJOR}/JMP.per" ]]; then
+          /bin/mv "$HOME/Library/Application Support/JMP/${MAJOR}/JMP.per" \\
+          "/Library/Application Support/JMP/${MAJOR}/JMP.per"
+      elif [[ -f "/var/root/Library/Application Support/JMP/${MAJOR}/JMP.per" ]]; then
+          /bin/mkdir -p "/Library/Application Support/JMP/${MAJOR}"
+          /bin/mv "/var/root/Library/Application Support/JMP/${MAJOR}/JMP.per" \\
+          "/Library/Application Support/JMP/${MAJOR}/JMP.per"
+          # change permissions
+          /bin/chmod 644 "/Library/Application Support/JMP/${MAJOR}/JMP.per"
+      else
+          echo "ERROR: JMP.per not found"
+          exit 1
+      fi
+      if [[ -f "/Library/Application Support/JMP/${MAJOR}/JMP.per" ]]; then
+          # define license location
+          /usr/bin/defaults write "/Library/Preferences/com.sas.jmp.plist" Setinit_${MAJOR}_Path "/Library/Application Support/JMP/${MAJOR}/JMP.per"
+      else
+          echo "ERROR: JMP.per not found in Library folder"
+          exit 1
+      fi
     file_mode: '0755'
     file_path: '%RECIPE_CACHE_DIR%/Scripts/postinstall'
 
diff --git a/_YAML/MunkiToolsCore/MunkiToolsCore.pkg.recipe.yaml b/_YAML/MunkiToolsCore/MunkiToolsCore.pkg.recipe.yaml
--- a/_YAML/MunkiToolsCore/MunkiToolsCore.pkg.recipe.yaml
+++ b/_YAML/MunkiToolsCore/MunkiToolsCore.pkg.recipe.yaml
@@ -1,4 +1,14 @@
-Description: "Note: munkitools does not include a code signature. If your organization requires code signature, it is recommended to internally sign the application.\n\nDownloads version 3 of the Munki tools via the official releases listing on GitHub. You can set INCLUDE_PRERELEASES to any value to have this recipe pull prerelease versions.\n\nThis recipe also extracts the core components, and repackages them for use in Jamf Pro.\nOther parts of munkitools are not repackaged.\n\nThis recipe cannot be overridden to pull a download from an alternate location such as munkibuilds.org - it will only download the official releases. For this, use the munkitools2-autobuild.munki recipe with a manually-provided DOWNLOAD_URL variable.\n\nThe GitHubReleasesInfoProvider processor used by this recipe also respects an input variable: ''sort_by_highest_tag_names'', which, if set, will ignore the post dates of the releases and instead sort descending by tag names according to LooseVersion semantics.\n"
+Description: |
+  Note: munkitools does not include a code signature. If your organization requires code signature, it is recommended to internally sign the application.
+  
+  Downloads version 3 of the Munki tools via the official releases listing on GitHub. You can set INCLUDE_PRERELEASES to any value to have this recipe pull prerelease versions.
+  
+  This recipe also extracts the core components, and repackages them for use in Jamf Pro.
+  Other parts of munkitools are not repackaged.
+  
+  This recipe cannot be overridden to pull a download from an alternate location such as munkibuilds.org - it will only download the official releases. For this, use the munkitools2-autobuild.munki recipe with a manually-provided DOWNLOAD_URL variable.
+  
+  The GitHubReleasesInfoProvider processor used by this recipe also respects an input variable: ''sort_by_highest_tag_names'', which, if set, will ignore the post dates of the releases and instead sort descending by tag names according to LooseVersion semantics.
 Identifier: com.github.grahampugh.recipes.pkg.MunkiToolsCore
 MinimumVersion: 0.5.0
 
@@ -51,7 +61,20 @@ Process:
 
 - Processor: FileCreator
   Arguments:
-    file_content: "#!/bin/bash\n## script to install Munki Core Tools and MunkiPython only\n\nDIR=$(dirname \"$0\")\n\n/usr/sbin/installer -applyChoiceChangesXML \"$DIR/choices.xml\" -pkg \"$DIR/munkitools-%version%.pkg\" -target /\n\nif (test $? = 0) then\n    echo \"Munki Core Tools installed.\"\nelse\n    echo \"ERROR: Munki Core Tools installation failed.\"\n    exit 1\nfi\n"
+    file_content: |
+      #!/bin/bash
+      ## script to install Munki Core Tools and MunkiPython only
+      
+      DIR=$(dirname "$0")
+      
+      /usr/sbin/installer -applyChoiceChangesXML "$DIR/choices.xml" -pkg "$DIR/munkitools-%version%.pkg" -target /
+      
+      if (test $? = 0) then
+          echo "Munki Core Tools installed."
+      else
+          echo "ERROR: Munki Core Tools installation failed."
+          exit 1
+      fi
     file_mode: '0755'
     file_path: '%RECIPE_CACHE_DIR%/Scripts/postinstall'
 
diff --git a/_YAML/_JSS_Script_Recipes/UninstallApplication.jss-script.recipe.yaml b/_YAML/_JSS_Script_Recipes/UninstallApplication.jss-script.recipe.yaml
--- a/_YAML/_JSS_Script_Recipes/UninstallApplication.jss-script.recipe.yaml
+++ b/_YAML/_JSS_Script_Recipes/UninstallApplication.jss-script.recipe.yaml
@@ -3,22 +3,121 @@ Identifier: com.github.grahampugh.recipes.jss-script.UninstallApplication
 MinimumVersion: 1.0.0
 
 Input:
-  SCRIPT_NAME: Uninstall %NAME%.sh
-  PKG_ID: None
-  PKG_ID_2: None
-  PKG_ID_3: None
-  PKG_ID_4: None
   PKG_ID_5: None
+  PKG_ID_4: None
+  PKG_ID_3: None
+  PKG_ID_2: None
+  PKG_ID: None
+  SCRIPT_NAME: Uninstall %NAME%.sh
 
 Process:
 - Processor: FileCreator
   Arguments:
-    file_content: "#!/bin/bash\n\n#######################################################################\n#\n# %SCRIPT_NAME% Script for Jamf Pro\n#\n# This script can delete apps that are sandboxed and live in /Applications\n#\n#######################################################################\n\n# Inputted variables\nappName=\"%JSS_INVENTORY_NAME%\"\n\nfunction silent_app_quit() {\n    # silently kill the application.\n    appName=\"$1\"\n    if [[ $(pgrep -ix \"$appName\") ]]; then\n    \techo \"Closing $appName\"\n    \t/usr/bin/osascript -e \"quit app \\\"$appName\\\"\"\n    \tsleep 1\n\n    \t# double-check\n    \tcountUp=0\n    \twhile [[ $countUp -le 10 ]]; do\n    \t\tif [[ -z $(pgrep -ix \"$appName\") ]]; then\n    \t\t\techo \"$appName closed.\"\n    \t\t\tbreak\n    \t\telse\n    \t\t\tlet countUp=$countUp+1\n    \t\t\tsleep 1\n    \t\tfi\n    \tdone\n        if [[ $(pgrep -x \"$appName\") ]]; then\n    \t    echo \"$appName failed to quit - killing.\"\n    \t    /usr/bin/pkill \"$appName\"\n        fi\n    fi\n}\n\nif [[ -z \"${appName}\" ]]; then\n    echo \"No application specified!\"\n    exit 1\nfi\n\n# quit the app if running\nsilent_app_quit \"$appName\"\n\n# Now remove the app\necho \"Removing application: ${appName}\"\n\n# Add .app to end when providing just a name e.g. \"TeamViewer\"\nif [[ ! $appName == *\".app\"* ]]; then\n\tappName=$appName\".app\"\nfi\n\n# Add standard path if none provided\nif [[ ! $appName == *\"/\"* ]]; then\n\tappToDelete=\"/Applications/$appName\"\nelse\n\tappToDelete=\"$appName\"\nfi\n\necho \"Application will be deleted: $appToDelete\"\n# Remove the application\n/bin/rm -rf \"${appToDelete}\"\n\necho \"Checking if $appName is actually deleted...\"\nif [[ -d \"${appToDelete}\" ]]; then\n    echo \"$appName failed to delete\"\nelse\n    echo \"$appName deleted successfully\"\nfi\n\n# Try to Forget the packages if we can find a match\n# Loop through the remaining parameters\npkg_1=\"%PKG_ID%\"\npkg_2=\"%PKG_ID_2%\"\npkg_3=\"%PKG_ID_3%\"\npkg_4=\"%PKG_ID_4%\"\npkg_5=\"%PKG_ID_5%\"\nfor (( i = 1; i < 5; i++ )); do\n    pkg_id=pkg_$i\n    if [[ ${!pkg_id} != \"None\" ]]; then\n        echo \"Forgetting package ${!pkg_id}...\"\n        /usr/sbin/pkgutil --pkgs | /usr/bin/grep -i \"${!pkg_id}\" | /usr/bin/xargs /usr/bin/sudo /usr/sbin/pkgutil --forget\n    fi\ndone\n\necho \"$appName deletion complete\"\n"
+    file_content: |
+      #!/bin/bash
+      
+      #######################################################################
+      #
+      # %SCRIPT_NAME% Script for Jamf Pro
+      #
+      # This script can delete apps that are sandboxed and live in /Applications
+      #
+      #######################################################################
+      
+      # Inputted variables
+      appName="%JSS_INVENTORY_NAME%"
+      
+      function silent_app_quit() {
+          # silently kill the application.
+          appName="$1"
+          if [[ $(pgrep -ix "$appName") ]]; then
+              echo "Closing $appName"
+              /usr/bin/osascript -e "quit app \\"$appName\\""
+              sleep 1
+      
+              # double-check
+              countUp=0
+              while [[ $countUp -le 10 ]]; do
+                  if [[ -z $(pgrep -ix "$appName") ]]; then
+                      echo "$appName closed."
+                      break
+                  else
+                      let countUp=$countUp+1
+                      sleep 1
+                  fi
+              done
+              if [[ $(pgrep -x "$appName") ]]; then
+                  echo "$appName failed to quit - killing."
+                  /usr/bin/pkill "$appName"
+              fi
+          fi
+      }
+      
+      if [[ -z "${appName}" ]]; then
+          echo "No application specified!"
+          exit 1
+      fi
+      
+      # quit the app if running
+      silent_app_quit "$appName"
+      
+      # Now remove the app
+      echo "Removing application: ${appName}"
+      
+      # Add .app to end when providing just a name e.g. "TeamViewer"
+      if [[ ! $appName == *".app"* ]]; then
+          appName=$appName".app"
+      fi
+      
+      # Add standard path if none provided
+      if [[ ! $appName == *"/"* ]]; then
+          appToDelete="/Applications/$appName"
+      else
+          appToDelete="$appName"
+      fi
+      
+      echo "Application will be deleted: $appToDelete"
+      # Remove the application
+      /bin/rm -rf "${appToDelete}"
+      
+      echo "Checking if $appName is actually deleted..."
+      if [[ -d "${appToDelete}" ]]; then
+          echo "$appName failed to delete"
+      else
+          echo "$appName deleted successfully"
+      fi
+      
+      # Try to Forget the packages if we can find a match
+      # Loop through the remaining parameters
+      pkg_1="%PKG_ID%"
+      pkg_2="%PKG_ID_2%"
+      pkg_3="%PKG_ID_3%"
+      pkg_4="%PKG_ID_4%"
+      pkg_5="%PKG_ID_5%"
+      for (( i = 1; i < 5; i++ )); do
+          pkg_id=pkg_$i
+          if [[ ${!pkg_id} != "None" ]]; then
+              echo "Forgetting package ${!pkg_id}..."
+              /usr/sbin/pkgutil --pkgs | /usr/bin/grep -i "${!pkg_id}" | /usr/bin/xargs /usr/bin/sudo /usr/sbin/pkgutil --forget
+          fi
+      done
+      
+      echo "$appName deletion complete"
     file_mode: '0755'
     file_path: '%RECIPE_DIR%/%NAME%-uninstall.sh'
 
 - Processor: FileCreator
   Arguments:
-    file_content: "<script>\n    <name>%NAME%-uninstall.sh</name>\n    <category>Uninstallers</category>\n    <filename>%NAME%-uninstall.sh</filename>\n    <info />\n    <notes />\n    <priority>After</priority>\n    <parameters />\n    <os_requirements />\n</script>\n"
+    file_content: |
+      <script>
+          <name>%NAME%-uninstall.sh</name>
+          <category>Uninstallers</category>
+          <filename>%NAME%-uninstall.sh</filename>
+          <info />
+          <notes />
+          <priority>After</priority>
+          <parameters />
+          <os_requirements />
+      </script>
     file_mode: '0755'
     file_path: '%RECIPE_DIR%/%NAME%-ScriptTemplate-uninstall.xml'
